### ISSUE TITLE
Error during common_setup event phase, can't extract

### ISSUE THREAD

**Issue by kutsen39** [jaquadro/StorageDrawers#1121]
Hi! I'm using Forge v. 1.20.2-forge-48.1.0 and Storage Drawers v. 1.210.1-12.0.2 and I get an error during loading.

`encountered an error during the common_setup event phase
 java.lang.NoClassDefFoundError: net/minecraftforge/network/NetworkRegistry$ChannelBuilder`

I've never played Java with mods, and it's been awhile since I've played Java at all. Can you help?

**Comment by jaquadro** [comment]
This was due to the mod not supporting those newer versions, though updates for newer versions did get published through July and August.

Sometimes a mod built for a version like 1.20.1 will still work on a minor upgrade like 1.20.2 or 1.20.3, so it can be worth trying, but it is not guaranteed.  In this particular case, Mojang made really big changes in their minor version updates.
